apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgeit-fe
  namespace: budgeit-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budgeit-fe
  template:
    metadata:
      labels:
        app: budgeit-fe
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      containers:
        - name: budgeit-fe
          image: ghcr.io/budgeit-app/budgeit-fe:211fbf43a2a5947e3deb752f5071be5e93695574
          ports:
            - containerPort: 80