apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgeit-fe
  namespace: budgeit-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budgeit-fe
  template:
    metadata:
      labels:
        app: budgeit-fe
    spec:
      containers:
        - name: budgeit-fe
          image: ghcr.io/budgeit-app/budgeit-fe:2f18eb129db5c0fc31be9c4aa2ee6d591adac208
          ports:
            - containerPort: 80